### ISSUE TITLE
I'm getting error "cannot find symbol variable Secrets:335"

### ISSUE THREAD

**Issue by rpcribari** [t3mr0i/ChatGPTGlass#4]
Right now I'm using Giraffe 2022.3.1 Patch 2 of Android Studio. I've put the Secrets.java file in the src folder with my API key entered. Any ideas? 

![Screenshot 2024-07-13 071227](https://github.com/user-attachments/assets/e6763cdb-c1ef-48a2-a276-7889628b682c)
![srcfolder](https://github.com/user-attachments/assets/195f9988-8ed3-4015-9f29-9f5c7ffa2c59)

**Comment by rpcribari** [comment]
I replaced Secrets.API_Key directly with my api key and it builds now. When I ask a question the response isn't displayed. Just goes right back to press touchpad screen.

**Comment by t3mr0i** [comment]
I have a new version in the works which will ask to scan a QR code for that secrets API key. I hope to be able to finish it this week or next.

**Comment by t3mr0i** [comment]
> I replaced Secrets.API_Key directly with my api key and it builds now. When I ask a question the response isn't displayed. Just goes right back to press touchpad screen.

That happens if you don't have credits. It should have a more graceful close. Maybe I have time to implement that soon.

**Comment by t3mr0i** [comment]
You only need credits on your api account.
