### ISSUE TITLE
Request for a Google Search version of this app.

### ISSUE THREAD

**Issue by rpcribari** [t3mr0i/ChatGPTGlass#5]
How hard would it be to convert this over to use Google Search instead? You could singlehandedly restore full functionality back to Glass if you did. "Help me Obi-Wan Kenobi. You're my only hope." I haven't done any programming for 24 years so the likelihood of me being able to figure it out myself is zero.

Thanks for considering.

**Comment by t3mr0i** [comment]
Hi there, actually there is a version I did for the knowledge graph:

https://youtu.be/jcKXjO-XS7c?si=39vv1XxR4IIQPWM5

I can see if i have the source code here somewhere. :)

**Comment by rpcribari** [comment]
Awesome! Thank you!!! 👍
